spring.application.name=kaizen-baiten-api

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.public.key=${JWT_PUBLIC_KEY}
jwt.private.key=${JWT_PRIVATE_KEY}